name: Automated PR Validation
on: 
  pull_request:
      types: [opened, edited, synchronize, reopened]
  
  workflow_dispatch:
    inputs:
      prNum:
        description: 'PR Number to run against'
        required: false
        default: '9'
      PRTitleValidationRequired:
        decription: 'Flag to disabled pull-request title validation'
        required: true
        default: true
      prTitleTemplate:
        description: 'Regex to validate PR Title'
        required: false
        default: 'IH-\d+:[\w\-]{36}:type\-[data|script]+:.+'
      scriptTypeAllowedExtensionsCSV:
        description: 'For PR of "script" type, which file extensions are allowed (each separated by comma)'
        required: true
        default: '.bdf,.bdh'
      dataTypeAllowedExtensionsCSV:
        description: 'For PR of "data" type, which file extensions are allowed (each separated by comma)'
        required: true
        default: '.csv,.dll,.txt,.exe,.config'
      AdditionalInfo:
        description: 'Anything to add to the Workflow run'
        required: false
        default: 'Test'

jobs:
  Validate:
    name: ${{ github.event.inputs.AdditionalInfo }} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
